name: field_data_bDEV
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.10.0
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - flake8==4.0.1
      - gdown==4.4.0
      - ipykernel==6.9.2
      - ipython==8.1.1
      - ipython-genutils==0.2.0
      - jupyter-client==7.1.2
      - jupyter-core==4.9.2
      - jupyter-server==1.15.6
      - jupyterlab==3.3.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.11.2
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.3
      - numpy==1.22.3
      - pandas==1.4.1
      - scipy==1.8.0
      